// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addlogin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlogin));
        
        string IMigrationMetadata.Id
        {
            get { return "202105181517227_add-login"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
